require('config/options')
require('config/lazy')
require('config/neovide')
require('config/keymaps')
require('core/colors')
require('config/autocmds')
require('core/functions')
require('config/read-terminal-theme')
